// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_POSLINKMANAGE_H_
#define PIGEON_POSLINKMANAGE_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace POSLinkManage {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class POSLinkManageApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


enum class ManageTouchscreenStatus {
  NotSet = 0,
  Use = 1,
  NotUse = 2
};

enum class ManageAppActivated {
  NotSet = 0,
  Activated = 1,
  NotActivated = 2
};

enum class ManageProtocolFlag {
  NotSet = 0,
  Visa1 = 1,
  Json = 2
};

enum class ManageUploadFlag {
  NotUploadToHost = 0,
  UploadToHost = 1
};

enum class ManageEdcType {
  NotSet = 0,
  All = 1,
  Credit = 2,
  Debit = 3,
  Ebt = 4,
  Gift = 5,
  Loyalty = 6,
  Cash = 7,
  QrPayment = 8
};

enum class ManageContinuousScreen {
  NotSet = 0,
  Default = 1,
  NotGoToIdleScreen = 2
};

enum class ManageVasMode {
  NotSet = 0,
  VasOnly = 1,
  VasAndPayment = 2,
  VasOrPayment = 3,
  PaymentOnly = 4
};

enum class ManageSecurity {
  NotSet = 0,
  Normal = 1,
  Securely = 2,
  PreSignature = 3,
  NeedNotARightAuth = 4
};

enum class ManageServiceState {
  NotSet = 0,
  Unspecified = 1,
  Success = 2,
  InvalidFormat = 3,
  InvalidValue = 4
};

enum class ManageUpdateOperation {
  NotSet = 0,
  NoOperation = 1,
  RemoveServiceObject = 2,
  SetBalance = 3,
  AddBalance = 4,
  SubtractBalance = 5,
  Free = 6
};

enum class ManageNewServiceType {
  NotSet = 0,
  Unspecified = 1,
  Valuable = 2,
  Receipt = 3,
  Survey = 4,
  Goods = 5,
  Signup = 6
};

enum class ManageEndTap {
  NotSet = 0,
  NormalFlow = 1,
  StopTapSession = 2
};

enum class ManageOseToPpse {
  NotSet = 0,
  NormalFlow = 1,
  StopVasAndDoPaymentDirectly = 2
};

enum class ManageUrlMode {
  NotSet = 0,
  FullVasMode = 1,
  UrlMode = 2
};

enum class ManageFileType {
  NotSet = 0,
  ResourceFile = 1,
  OfflineRkiKeyFile = 2,
  InstallationPackageFile = 3,
  licenseFile = 4
};

enum class ManageTargetDevice {
  NotSet = 0,
  Terminal = 1,
  ExternalPinpad = 2
};

// Generated class from Pigeon that represents data sent in messages.
class ManageMultiMerchant {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageMultiMerchant();

  // Constructs an object setting all fields.
  explicit ManageMultiMerchant(
    const std::string* multi_merchant_id,
    const std::string* multi_merchant_name);

  const std::string* multi_merchant_id() const;
  void set_multi_merchant_id(const std::string_view* value_arg);
  void set_multi_merchant_id(std::string_view value_arg);

  const std::string* multi_merchant_name() const;
  void set_multi_merchant_name(const std::string_view* value_arg);
  void set_multi_merchant_name(std::string_view value_arg);


 private:
  static ManageMultiMerchant FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageSetVariableRequest;
  friend class ManageGetVariableRequest;
  friend class ManageGetVariableResponse;
  friend class ManageSetVariableResponse;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> multi_merchant_id_;
  std::optional<std::string> multi_merchant_name_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageSetVariableRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageSetVariableRequest();

  // Constructs an object setting all fields.
  explicit ManageSetVariableRequest(
    const ManageEdcType* edc_type,
    const std::string* variable_name1,
    const std::string* variable_value1,
    const std::string* variable_name2,
    const std::string* variable_value2,
    const std::string* variable_name3,
    const std::string* variable_value3,
    const std::string* variable_name4,
    const std::string* variable_value4,
    const std::string* variable_name5,
    const std::string* variable_value5,
    const ManageMultiMerchant* multi_merchant);

  const ManageEdcType* edc_type() const;
  void set_edc_type(const ManageEdcType* value_arg);
  void set_edc_type(const ManageEdcType& value_arg);

  const std::string* variable_name1() const;
  void set_variable_name1(const std::string_view* value_arg);
  void set_variable_name1(std::string_view value_arg);

  const std::string* variable_value1() const;
  void set_variable_value1(const std::string_view* value_arg);
  void set_variable_value1(std::string_view value_arg);

  const std::string* variable_name2() const;
  void set_variable_name2(const std::string_view* value_arg);
  void set_variable_name2(std::string_view value_arg);

  const std::string* variable_value2() const;
  void set_variable_value2(const std::string_view* value_arg);
  void set_variable_value2(std::string_view value_arg);

  const std::string* variable_name3() const;
  void set_variable_name3(const std::string_view* value_arg);
  void set_variable_name3(std::string_view value_arg);

  const std::string* variable_value3() const;
  void set_variable_value3(const std::string_view* value_arg);
  void set_variable_value3(std::string_view value_arg);

  const std::string* variable_name4() const;
  void set_variable_name4(const std::string_view* value_arg);
  void set_variable_name4(std::string_view value_arg);

  const std::string* variable_value4() const;
  void set_variable_value4(const std::string_view* value_arg);
  void set_variable_value4(std::string_view value_arg);

  const std::string* variable_name5() const;
  void set_variable_name5(const std::string_view* value_arg);
  void set_variable_name5(std::string_view value_arg);

  const std::string* variable_value5() const;
  void set_variable_value5(const std::string_view* value_arg);
  void set_variable_value5(std::string_view value_arg);

  const ManageMultiMerchant* multi_merchant() const;
  void set_multi_merchant(const ManageMultiMerchant* value_arg);
  void set_multi_merchant(const ManageMultiMerchant& value_arg);


 private:
  static ManageSetVariableRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageEdcType> edc_type_;
  std::optional<std::string> variable_name1_;
  std::optional<std::string> variable_value1_;
  std::optional<std::string> variable_name2_;
  std::optional<std::string> variable_value2_;
  std::optional<std::string> variable_name3_;
  std::optional<std::string> variable_value3_;
  std::optional<std::string> variable_name4_;
  std::optional<std::string> variable_value4_;
  std::optional<std::string> variable_name5_;
  std::optional<std::string> variable_value5_;
  std::optional<ManageMultiMerchant> multi_merchant_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageNewService {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageNewService();

  // Constructs an object setting all fields.
  explicit ManageNewService(
    const ManageNewServiceType* type,
    const std::string* title,
    const std::string* url);

  const ManageNewServiceType* type() const;
  void set_type(const ManageNewServiceType* value_arg);
  void set_type(const ManageNewServiceType& value_arg);

  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  const std::string* url() const;
  void set_url(const std::string_view* value_arg);
  void set_url(std::string_view value_arg);


 private:
  static ManageNewService FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageNewServiceType> type_;
  std::optional<std::string> title_;
  std::optional<std::string> url_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageServiceUpdate {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageServiceUpdate();

  // Constructs an object setting all fields.
  explicit ManageServiceUpdate(
    const std::string* update_id,
    const ManageUpdateOperation* update_operation,
    const std::string* update_payload);

  const std::string* update_id() const;
  void set_update_id(const std::string_view* value_arg);
  void set_update_id(std::string_view value_arg);

  const ManageUpdateOperation* update_operation() const;
  void set_update_operation(const ManageUpdateOperation* value_arg);
  void set_update_operation(const ManageUpdateOperation& value_arg);

  const std::string* update_payload() const;
  void set_update_payload(const std::string_view* value_arg);
  void set_update_payload(std::string_view value_arg);


 private:
  static ManageServiceUpdate FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> update_id_;
  std::optional<ManageUpdateOperation> update_operation_;
  std::optional<std::string> update_payload_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageServiceUsage {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageServiceUsage();

  // Constructs an object setting all fields.
  explicit ManageServiceUsage(
    const std::string* usage_id,
    const ManageServiceState* state,
    const std::string* title,
    const std::string* describe);

  const std::string* usage_id() const;
  void set_usage_id(const std::string_view* value_arg);
  void set_usage_id(std::string_view value_arg);

  const ManageServiceState* state() const;
  void set_state(const ManageServiceState* value_arg);
  void set_state(const ManageServiceState& value_arg);

  const std::string* title() const;
  void set_title(const std::string_view* value_arg);
  void set_title(std::string_view value_arg);

  const std::string* describe() const;
  void set_describe(const std::string_view* value_arg);
  void set_describe(std::string_view value_arg);


 private:
  static ManageServiceUsage FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> usage_id_;
  std::optional<ManageServiceState> state_;
  std::optional<std::string> title_;
  std::optional<std::string> describe_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGoogleSmartTapCapBitmap {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGoogleSmartTapCapBitmap();

  // Constructs an object setting all fields.
  explicit ManageGoogleSmartTapCapBitmap(
    const bool* stand_alone,
    const bool* semi_integrated,
    const bool* unattended,
    const bool* online,
    const bool* offline,
    const bool* mmp,
    const bool* zlib_support,
    const bool* printer,
    const bool* printer_graphics,
    const bool* display,
    const bool* images,
    const bool* audio,
    const bool* animation,
    const bool* video,
    const bool* support_payment,
    const bool* support_digital_receipt,
    const bool* support_service_issuance,
    const bool* support_ota_pos_data,
    const bool* online_pin,
    const bool* cd_pin,
    const bool* signature,
    const bool* no_cvm,
    const bool* device_generated_code,
    const bool* sp_generated_code,
    const bool* id_capture,
    const bool* bio_metric);

  const bool* stand_alone() const;
  void set_stand_alone(const bool* value_arg);
  void set_stand_alone(bool value_arg);

  const bool* semi_integrated() const;
  void set_semi_integrated(const bool* value_arg);
  void set_semi_integrated(bool value_arg);

  const bool* unattended() const;
  void set_unattended(const bool* value_arg);
  void set_unattended(bool value_arg);

  const bool* online() const;
  void set_online(const bool* value_arg);
  void set_online(bool value_arg);

  const bool* offline() const;
  void set_offline(const bool* value_arg);
  void set_offline(bool value_arg);

  const bool* mmp() const;
  void set_mmp(const bool* value_arg);
  void set_mmp(bool value_arg);

  const bool* zlib_support() const;
  void set_zlib_support(const bool* value_arg);
  void set_zlib_support(bool value_arg);

  const bool* printer() const;
  void set_printer(const bool* value_arg);
  void set_printer(bool value_arg);

  const bool* printer_graphics() const;
  void set_printer_graphics(const bool* value_arg);
  void set_printer_graphics(bool value_arg);

  const bool* display() const;
  void set_display(const bool* value_arg);
  void set_display(bool value_arg);

  const bool* images() const;
  void set_images(const bool* value_arg);
  void set_images(bool value_arg);

  const bool* audio() const;
  void set_audio(const bool* value_arg);
  void set_audio(bool value_arg);

  const bool* animation() const;
  void set_animation(const bool* value_arg);
  void set_animation(bool value_arg);

  const bool* video() const;
  void set_video(const bool* value_arg);
  void set_video(bool value_arg);

  const bool* support_payment() const;
  void set_support_payment(const bool* value_arg);
  void set_support_payment(bool value_arg);

  const bool* support_digital_receipt() const;
  void set_support_digital_receipt(const bool* value_arg);
  void set_support_digital_receipt(bool value_arg);

  const bool* support_service_issuance() const;
  void set_support_service_issuance(const bool* value_arg);
  void set_support_service_issuance(bool value_arg);

  const bool* support_ota_pos_data() const;
  void set_support_ota_pos_data(const bool* value_arg);
  void set_support_ota_pos_data(bool value_arg);

  const bool* online_pin() const;
  void set_online_pin(const bool* value_arg);
  void set_online_pin(bool value_arg);

  const bool* cd_pin() const;
  void set_cd_pin(const bool* value_arg);
  void set_cd_pin(bool value_arg);

  const bool* signature() const;
  void set_signature(const bool* value_arg);
  void set_signature(bool value_arg);

  const bool* no_cvm() const;
  void set_no_cvm(const bool* value_arg);
  void set_no_cvm(bool value_arg);

  const bool* device_generated_code() const;
  void set_device_generated_code(const bool* value_arg);
  void set_device_generated_code(bool value_arg);

  const bool* sp_generated_code() const;
  void set_sp_generated_code(const bool* value_arg);
  void set_sp_generated_code(bool value_arg);

  const bool* id_capture() const;
  void set_id_capture(const bool* value_arg);
  void set_id_capture(bool value_arg);

  const bool* bio_metric() const;
  void set_bio_metric(const bool* value_arg);
  void set_bio_metric(bool value_arg);


 private:
  static ManageGoogleSmartTapCapBitmap FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageGoogleSmartTapPushService;
  friend class ManageGoogleSmartTap;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<bool> stand_alone_;
  std::optional<bool> semi_integrated_;
  std::optional<bool> unattended_;
  std::optional<bool> online_;
  std::optional<bool> offline_;
  std::optional<bool> mmp_;
  std::optional<bool> zlib_support_;
  std::optional<bool> printer_;
  std::optional<bool> printer_graphics_;
  std::optional<bool> display_;
  std::optional<bool> images_;
  std::optional<bool> audio_;
  std::optional<bool> animation_;
  std::optional<bool> video_;
  std::optional<bool> support_payment_;
  std::optional<bool> support_digital_receipt_;
  std::optional<bool> support_service_issuance_;
  std::optional<bool> support_ota_pos_data_;
  std::optional<bool> online_pin_;
  std::optional<bool> cd_pin_;
  std::optional<bool> signature_;
  std::optional<bool> no_cvm_;
  std::optional<bool> device_generated_code_;
  std::optional<bool> sp_generated_code_;
  std::optional<bool> id_capture_;
  std::optional<bool> bio_metric_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGoogleSmartTapPushService {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGoogleSmartTapPushService();

  // Constructs an object setting all fields.
  explicit ManageGoogleSmartTapPushService(
    const ManageSecurity* security,
    const ManageGoogleSmartTapCapBitmap* google_smart_tap_cap,
    const std::string* collect_id,
    const flutter::EncodableList* google_service_usage,
    const flutter::EncodableList* google_service_update,
    const flutter::EncodableList* google_new_service,
    const ManageEndTap* end_tap);

  const ManageSecurity* security() const;
  void set_security(const ManageSecurity* value_arg);
  void set_security(const ManageSecurity& value_arg);

  const ManageGoogleSmartTapCapBitmap* google_smart_tap_cap() const;
  void set_google_smart_tap_cap(const ManageGoogleSmartTapCapBitmap* value_arg);
  void set_google_smart_tap_cap(const ManageGoogleSmartTapCapBitmap& value_arg);

  const std::string* collect_id() const;
  void set_collect_id(const std::string_view* value_arg);
  void set_collect_id(std::string_view value_arg);

  const flutter::EncodableList* google_service_usage() const;
  void set_google_service_usage(const flutter::EncodableList* value_arg);
  void set_google_service_usage(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* google_service_update() const;
  void set_google_service_update(const flutter::EncodableList* value_arg);
  void set_google_service_update(const flutter::EncodableList& value_arg);

  const flutter::EncodableList* google_new_service() const;
  void set_google_new_service(const flutter::EncodableList* value_arg);
  void set_google_new_service(const flutter::EncodableList& value_arg);

  const ManageEndTap* end_tap() const;
  void set_end_tap(const ManageEndTap* value_arg);
  void set_end_tap(const ManageEndTap& value_arg);


 private:
  static ManageGoogleSmartTapPushService FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageVasPushDataRequest;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageSecurity> security_;
  std::optional<ManageGoogleSmartTapCapBitmap> google_smart_tap_cap_;
  std::optional<std::string> collect_id_;
  std::optional<flutter::EncodableList> google_service_usage_;
  std::optional<flutter::EncodableList> google_service_update_;
  std::optional<flutter::EncodableList> google_new_service_;
  std::optional<ManageEndTap> end_tap_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageRebootRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageRebootRequest();

  // Constructs an object setting all fields.
  explicit ManageRebootRequest(const std::string* class_i_d);

  const std::string* class_i_d() const;
  void set_class_i_d(const std::string_view* value_arg);
  void set_class_i_d(std::string_view value_arg);


 private:
  static ManageRebootRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> class_i_d_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageUpdateResourceFileRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageUpdateResourceFileRequest();

  // Constructs an object setting all fields.
  explicit ManageUpdateResourceFileRequest(
    const std::string* file_url,
    const ManageFileType* file_type,
    const ManageTargetDevice* target_device);

  const std::string* file_url() const;
  void set_file_url(const std::string_view* value_arg);
  void set_file_url(std::string_view value_arg);

  const ManageFileType* file_type() const;
  void set_file_type(const ManageFileType* value_arg);
  void set_file_type(const ManageFileType& value_arg);

  const ManageTargetDevice* target_device() const;
  void set_target_device(const ManageTargetDevice* value_arg);
  void set_target_device(const ManageTargetDevice& value_arg);


 private:
  static ManageUpdateResourceFileRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> file_url_;
  std::optional<ManageFileType> file_type_;
  std::optional<ManageTargetDevice> target_device_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGetVariableRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGetVariableRequest();

  // Constructs an object setting all fields.
  explicit ManageGetVariableRequest(
    const ManageEdcType* edc_type,
    const std::string* variable_name1,
    const std::string* variable_name2,
    const std::string* variable_name3,
    const std::string* variable_name4,
    const std::string* variable_name5,
    const ManageMultiMerchant* multi_merchant);

  const ManageEdcType* edc_type() const;
  void set_edc_type(const ManageEdcType* value_arg);
  void set_edc_type(const ManageEdcType& value_arg);

  const std::string* variable_name1() const;
  void set_variable_name1(const std::string_view* value_arg);
  void set_variable_name1(std::string_view value_arg);

  const std::string* variable_name2() const;
  void set_variable_name2(const std::string_view* value_arg);
  void set_variable_name2(std::string_view value_arg);

  const std::string* variable_name3() const;
  void set_variable_name3(const std::string_view* value_arg);
  void set_variable_name3(std::string_view value_arg);

  const std::string* variable_name4() const;
  void set_variable_name4(const std::string_view* value_arg);
  void set_variable_name4(std::string_view value_arg);

  const std::string* variable_name5() const;
  void set_variable_name5(const std::string_view* value_arg);
  void set_variable_name5(std::string_view value_arg);

  const ManageMultiMerchant* multi_merchant() const;
  void set_multi_merchant(const ManageMultiMerchant* value_arg);
  void set_multi_merchant(const ManageMultiMerchant& value_arg);


 private:
  static ManageGetVariableRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageEdcType> edc_type_;
  std::optional<std::string> variable_name1_;
  std::optional<std::string> variable_name2_;
  std::optional<std::string> variable_name3_;
  std::optional<std::string> variable_name4_;
  std::optional<std::string> variable_name5_;
  std::optional<ManageMultiMerchant> multi_merchant_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageResetScreenRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageResetScreenRequest();

  // Constructs an object setting all fields.
  explicit ManageResetScreenRequest(const std::string* class_i_d);

  const std::string* class_i_d() const;
  void set_class_i_d(const std::string_view* value_arg);
  void set_class_i_d(std::string_view value_arg);


 private:
  static ManageResetScreenRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> class_i_d_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageApplePayVas {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageApplePayVas();

  // Constructs an object setting all fields.
  explicit ManageApplePayVas(
    const std::string* merchant_id,
    const ManageUrlMode* url_mode,
    const std::string* url,
    const flutter::EncodableList* key_file_mapping);

  const std::string* merchant_id() const;
  void set_merchant_id(const std::string_view* value_arg);
  void set_merchant_id(std::string_view value_arg);

  const ManageUrlMode* url_mode() const;
  void set_url_mode(const ManageUrlMode* value_arg);
  void set_url_mode(const ManageUrlMode& value_arg);

  const std::string* url() const;
  void set_url(const std::string_view* value_arg);
  void set_url(std::string_view value_arg);

  const flutter::EncodableList* key_file_mapping() const;
  void set_key_file_mapping(const flutter::EncodableList* value_arg);
  void set_key_file_mapping(const flutter::EncodableList& value_arg);


 private:
  static ManageApplePayVas FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageSetApplePayVasParametersRequest;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> merchant_id_;
  std::optional<ManageUrlMode> url_mode_;
  std::optional<std::string> url_;
  std::optional<flutter::EncodableList> key_file_mapping_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGetSignatureRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGetSignatureRequest();

  // Constructs an object setting all fields.
  explicit ManageGetSignatureRequest(const std::string* class_i_d);

  const std::string* class_i_d() const;
  void set_class_i_d(const std::string_view* value_arg);
  void set_class_i_d(std::string_view value_arg);


 private:
  static ManageGetSignatureRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> class_i_d_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageSetApplePayVasParametersRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageSetApplePayVasParametersRequest();

  // Constructs an object setting all fields.
  explicit ManageSetApplePayVasParametersRequest(
    const ManageVasMode* vas_mode,
    const ManageApplePayVas* apple_pay_vas_data);

  const ManageVasMode* vas_mode() const;
  void set_vas_mode(const ManageVasMode* value_arg);
  void set_vas_mode(const ManageVasMode& value_arg);

  const ManageApplePayVas* apple_pay_vas_data() const;
  void set_apple_pay_vas_data(const ManageApplePayVas* value_arg);
  void set_apple_pay_vas_data(const ManageApplePayVas& value_arg);


 private:
  static ManageSetApplePayVasParametersRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageVasMode> vas_mode_;
  std::optional<ManageApplePayVas> apple_pay_vas_data_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageClearCardBufferRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageClearCardBufferRequest();

  // Constructs an object setting all fields.
  explicit ManageClearCardBufferRequest(const std::string* class_i_d);

  const std::string* class_i_d() const;
  void set_class_i_d(const std::string_view* value_arg);
  void set_class_i_d(std::string_view value_arg);


 private:
  static ManageClearCardBufferRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> class_i_d_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageCheckFileRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageCheckFileRequest();

  // Constructs an object setting all fields.
  explicit ManageCheckFileRequest(const std::string* file_name);

  const std::string* file_name() const;
  void set_file_name(const std::string_view* value_arg);
  void set_file_name(std::string_view value_arg);


 private:
  static ManageCheckFileRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> file_name_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGoogleServiceTypeBitmap {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGoogleServiceTypeBitmap();

  // Constructs an object setting all fields.
  explicit ManageGoogleServiceTypeBitmap(
    const bool* all_services,
    const bool* all_services_except_ppse,
    const bool* ppse,
    const bool* loyalty,
    const bool* offer,
    const bool* gift_card1,
    const bool* private_label_card,
    const bool* cloud_based_wallet,
    const bool* mobile_marketing_platform,
    const bool* wallet_customer);

  const bool* all_services() const;
  void set_all_services(const bool* value_arg);
  void set_all_services(bool value_arg);

  const bool* all_services_except_ppse() const;
  void set_all_services_except_ppse(const bool* value_arg);
  void set_all_services_except_ppse(bool value_arg);

  const bool* ppse() const;
  void set_ppse(const bool* value_arg);
  void set_ppse(bool value_arg);

  const bool* loyalty() const;
  void set_loyalty(const bool* value_arg);
  void set_loyalty(bool value_arg);

  const bool* offer() const;
  void set_offer(const bool* value_arg);
  void set_offer(bool value_arg);

  const bool* gift_card1() const;
  void set_gift_card1(const bool* value_arg);
  void set_gift_card1(bool value_arg);

  const bool* private_label_card() const;
  void set_private_label_card(const bool* value_arg);
  void set_private_label_card(bool value_arg);

  const bool* cloud_based_wallet() const;
  void set_cloud_based_wallet(const bool* value_arg);
  void set_cloud_based_wallet(bool value_arg);

  const bool* mobile_marketing_platform() const;
  void set_mobile_marketing_platform(const bool* value_arg);
  void set_mobile_marketing_platform(bool value_arg);

  const bool* wallet_customer() const;
  void set_wallet_customer(const bool* value_arg);
  void set_wallet_customer(bool value_arg);


 private:
  static ManageGoogleServiceTypeBitmap FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageGoogleSmartTap;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<bool> all_services_;
  std::optional<bool> all_services_except_ppse_;
  std::optional<bool> ppse_;
  std::optional<bool> loyalty_;
  std::optional<bool> offer_;
  std::optional<bool> gift_card1_;
  std::optional<bool> private_label_card_;
  std::optional<bool> cloud_based_wallet_;
  std::optional<bool> mobile_marketing_platform_;
  std::optional<bool> wallet_customer_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGoogleSmartTap {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGoogleSmartTap();

  // Constructs an object setting all fields.
  explicit ManageGoogleSmartTap(
    const ManageGoogleSmartTapCapBitmap* google_smart_tap_cap,
    const std::string* collect_id,
    const std::string* store_local_id,
    const std::string* terminal_id,
    const std::string* merchant_name,
    const std::string* merchant_category,
    const ManageGoogleServiceTypeBitmap* service_type,
    const ManageSecurity* security,
    const ManageEndTap* end_tap,
    const ManageOseToPpse* ose_to_ppse);

  const ManageGoogleSmartTapCapBitmap* google_smart_tap_cap() const;
  void set_google_smart_tap_cap(const ManageGoogleSmartTapCapBitmap* value_arg);
  void set_google_smart_tap_cap(const ManageGoogleSmartTapCapBitmap& value_arg);

  const std::string* collect_id() const;
  void set_collect_id(const std::string_view* value_arg);
  void set_collect_id(std::string_view value_arg);

  const std::string* store_local_id() const;
  void set_store_local_id(const std::string_view* value_arg);
  void set_store_local_id(std::string_view value_arg);

  const std::string* terminal_id() const;
  void set_terminal_id(const std::string_view* value_arg);
  void set_terminal_id(std::string_view value_arg);

  const std::string* merchant_name() const;
  void set_merchant_name(const std::string_view* value_arg);
  void set_merchant_name(std::string_view value_arg);

  const std::string* merchant_category() const;
  void set_merchant_category(const std::string_view* value_arg);
  void set_merchant_category(std::string_view value_arg);

  const ManageGoogleServiceTypeBitmap* service_type() const;
  void set_service_type(const ManageGoogleServiceTypeBitmap* value_arg);
  void set_service_type(const ManageGoogleServiceTypeBitmap& value_arg);

  const ManageSecurity* security() const;
  void set_security(const ManageSecurity* value_arg);
  void set_security(const ManageSecurity& value_arg);

  const ManageEndTap* end_tap() const;
  void set_end_tap(const ManageEndTap* value_arg);
  void set_end_tap(const ManageEndTap& value_arg);

  const ManageOseToPpse* ose_to_ppse() const;
  void set_ose_to_ppse(const ManageOseToPpse* value_arg);
  void set_ose_to_ppse(const ManageOseToPpse& value_arg);


 private:
  static ManageGoogleSmartTap FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageSetGoogleSmartTapParametersRequest;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageGoogleSmartTapCapBitmap> google_smart_tap_cap_;
  std::optional<std::string> collect_id_;
  std::optional<std::string> store_local_id_;
  std::optional<std::string> terminal_id_;
  std::optional<std::string> merchant_name_;
  std::optional<std::string> merchant_category_;
  std::optional<ManageGoogleServiceTypeBitmap> service_type_;
  std::optional<ManageSecurity> security_;
  std::optional<ManageEndTap> end_tap_;
  std::optional<ManageOseToPpse> ose_to_ppse_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageSetGoogleSmartTapParametersRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageSetGoogleSmartTapParametersRequest();

  // Constructs an object setting all fields.
  explicit ManageSetGoogleSmartTapParametersRequest(
    const ManageVasMode* vas_mode,
    const ManageGoogleSmartTap* google_smart_tap_data);

  const ManageVasMode* vas_mode() const;
  void set_vas_mode(const ManageVasMode* value_arg);
  void set_vas_mode(const ManageVasMode& value_arg);

  const ManageGoogleSmartTap* google_smart_tap_data() const;
  void set_google_smart_tap_data(const ManageGoogleSmartTap* value_arg);
  void set_google_smart_tap_data(const ManageGoogleSmartTap& value_arg);


 private:
  static ManageSetGoogleSmartTapParametersRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageVasMode> vas_mode_;
  std::optional<ManageGoogleSmartTap> google_smart_tap_data_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageInitRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageInitRequest();

  // Constructs an object setting all fields.
  explicit ManageInitRequest(const std::string* class_i_d);

  const std::string* class_i_d() const;
  void set_class_i_d(const std::string_view* value_arg);
  void set_class_i_d(std::string_view value_arg);


 private:
  static ManageInitRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> class_i_d_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageVasPushDataRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageVasPushDataRequest();

  // Constructs an object setting all fields.
  explicit ManageVasPushDataRequest(
    const ManageVasMode* vas_mode,
    const ManageGoogleSmartTapPushService* google_smart_tap_push_service);

  const ManageVasMode* vas_mode() const;
  void set_vas_mode(const ManageVasMode* value_arg);
  void set_vas_mode(const ManageVasMode& value_arg);

  const ManageGoogleSmartTapPushService* google_smart_tap_push_service() const;
  void set_google_smart_tap_push_service(const ManageGoogleSmartTapPushService* value_arg);
  void set_google_smart_tap_push_service(const ManageGoogleSmartTapPushService& value_arg);


 private:
  static ManageVasPushDataRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageVasMode> vas_mode_;
  std::optional<ManageGoogleSmartTapPushService> google_smart_tap_push_service_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageDoSignatureRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageDoSignatureRequest();

  // Constructs an object setting all fields.
  explicit ManageDoSignatureRequest(
    const ManageUploadFlag* upload_flag,
    const std::string* host_reference_number,
    const ManageEdcType* edc_type,
    const std::string* timeout,
    const ManageContinuousScreen* continuous_screen);

  const ManageUploadFlag* upload_flag() const;
  void set_upload_flag(const ManageUploadFlag* value_arg);
  void set_upload_flag(const ManageUploadFlag& value_arg);

  const std::string* host_reference_number() const;
  void set_host_reference_number(const std::string_view* value_arg);
  void set_host_reference_number(std::string_view value_arg);

  const ManageEdcType* edc_type() const;
  void set_edc_type(const ManageEdcType* value_arg);
  void set_edc_type(const ManageEdcType& value_arg);

  const std::string* timeout() const;
  void set_timeout(const std::string_view* value_arg);
  void set_timeout(std::string_view value_arg);

  const ManageContinuousScreen* continuous_screen() const;
  void set_continuous_screen(const ManageContinuousScreen* value_arg);
  void set_continuous_screen(const ManageContinuousScreen& value_arg);


 private:
  static ManageDoSignatureRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<ManageUploadFlag> upload_flag_;
  std::optional<std::string> host_reference_number_;
  std::optional<ManageEdcType> edc_type_;
  std::optional<std::string> timeout_;
  std::optional<ManageContinuousScreen> continuous_screen_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageDeleteImageRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageDeleteImageRequest();

  // Constructs an object setting all fields.
  explicit ManageDeleteImageRequest(const std::string* image_name);

  const std::string* image_name() const;
  void set_image_name(const std::string_view* value_arg);
  void set_image_name(std::string_view value_arg);


 private:
  static ManageDeleteImageRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> image_name_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageSetGoogleSmartTapParametersResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageSetGoogleSmartTapParametersResponse();

  // Constructs an object setting all fields.
  explicit ManageSetGoogleSmartTapParametersResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageSetGoogleSmartTapParametersResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGetVariableResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGetVariableResponse();

  // Constructs an object setting all fields.
  explicit ManageGetVariableResponse(
    const std::string* response_code,
    const std::string* response_message,
    const std::string* variable_value1,
    const std::string* variable_value2,
    const std::string* variable_value3,
    const std::string* variable_value4,
    const std::string* variable_value5,
    const ManageMultiMerchant* multi_merchant);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);

  const std::string* variable_value1() const;
  void set_variable_value1(const std::string_view* value_arg);
  void set_variable_value1(std::string_view value_arg);

  const std::string* variable_value2() const;
  void set_variable_value2(const std::string_view* value_arg);
  void set_variable_value2(std::string_view value_arg);

  const std::string* variable_value3() const;
  void set_variable_value3(const std::string_view* value_arg);
  void set_variable_value3(std::string_view value_arg);

  const std::string* variable_value4() const;
  void set_variable_value4(const std::string_view* value_arg);
  void set_variable_value4(std::string_view value_arg);

  const std::string* variable_value5() const;
  void set_variable_value5(const std::string_view* value_arg);
  void set_variable_value5(std::string_view value_arg);

  const ManageMultiMerchant* multi_merchant() const;
  void set_multi_merchant(const ManageMultiMerchant* value_arg);
  void set_multi_merchant(const ManageMultiMerchant& value_arg);


 private:
  static ManageGetVariableResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;
  std::optional<std::string> variable_value1_;
  std::optional<std::string> variable_value2_;
  std::optional<std::string> variable_value3_;
  std::optional<std::string> variable_value4_;
  std::optional<std::string> variable_value5_;
  std::optional<ManageMultiMerchant> multi_merchant_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageRebootResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageRebootResponse();

  // Constructs an object setting all fields.
  explicit ManageRebootResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageRebootResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageDeleteImageResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageDeleteImageResponse();

  // Constructs an object setting all fields.
  explicit ManageDeleteImageResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageDeleteImageResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageResetScreenResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageResetScreenResponse();

  // Constructs an object setting all fields.
  explicit ManageResetScreenResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageResetScreenResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageVasPushDataResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageVasPushDataResponse();

  // Constructs an object setting all fields.
  explicit ManageVasPushDataResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageVasPushDataResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageDoSignatureResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageDoSignatureResponse();

  // Constructs an object setting all fields.
  explicit ManageDoSignatureResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageDoSignatureResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageClearCardBufferResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageClearCardBufferResponse();

  // Constructs an object setting all fields.
  explicit ManageClearCardBufferResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageClearCardBufferResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageCheckFileResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageCheckFileResponse();

  // Constructs an object setting all fields.
  explicit ManageCheckFileResponse(
    const std::string* response_code,
    const std::string* response_message,
    const std::string* check_sum);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);

  const std::string* check_sum() const;
  void set_check_sum(const std::string_view* value_arg);
  void set_check_sum(std::string_view value_arg);


 private:
  static ManageCheckFileResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;
  std::optional<std::string> check_sum_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageHardwareConfigurationBitmap {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageHardwareConfigurationBitmap();

  // Constructs an object setting all fields.
  explicit ManageHardwareConfigurationBitmap(
    const bool* magstripe,
    const bool* emv_chip,
    const bool* emv_contactless,
    const bool* camera_front,
    const bool* laser_scanner,
    const bool* camera_rear,
    const bool* printer,
    const bool* touchscreen);

  const bool* magstripe() const;
  void set_magstripe(const bool* value_arg);
  void set_magstripe(bool value_arg);

  const bool* emv_chip() const;
  void set_emv_chip(const bool* value_arg);
  void set_emv_chip(bool value_arg);

  const bool* emv_contactless() const;
  void set_emv_contactless(const bool* value_arg);
  void set_emv_contactless(bool value_arg);

  const bool* camera_front() const;
  void set_camera_front(const bool* value_arg);
  void set_camera_front(bool value_arg);

  const bool* laser_scanner() const;
  void set_laser_scanner(const bool* value_arg);
  void set_laser_scanner(bool value_arg);

  const bool* camera_rear() const;
  void set_camera_rear(const bool* value_arg);
  void set_camera_rear(bool value_arg);

  const bool* printer() const;
  void set_printer(const bool* value_arg);
  void set_printer(bool value_arg);

  const bool* touchscreen() const;
  void set_touchscreen(const bool* value_arg);
  void set_touchscreen(bool value_arg);


 private:
  static ManageHardwareConfigurationBitmap FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class ManageInitResponse;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<bool> magstripe_;
  std::optional<bool> emv_chip_;
  std::optional<bool> emv_contactless_;
  std::optional<bool> camera_front_;
  std::optional<bool> laser_scanner_;
  std::optional<bool> camera_rear_;
  std::optional<bool> printer_;
  std::optional<bool> touchscreen_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageInitResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageInitResponse();

  // Constructs an object setting all fields.
  explicit ManageInitResponse(
    const std::string* response_code,
    const std::string* response_message,
    const std::string* sn,
    const std::string* model_name,
    const std::string* os_version,
    const std::string* mac_address,
    const std::string* lines_per_screen,
    const std::string* chars_per_line,
    const std::string* app_name,
    const std::string* app_version,
    const std::string* wifi_mac,
    const ManageTouchscreenStatus* touchscreen,
    const ManageHardwareConfigurationBitmap* hardware_configuration_bitmap,
    const ManageAppActivated* app_activated,
    const std::string* license_expiry,
    const ManageProtocolFlag* protocol_flag);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);

  const std::string* sn() const;
  void set_sn(const std::string_view* value_arg);
  void set_sn(std::string_view value_arg);

  const std::string* model_name() const;
  void set_model_name(const std::string_view* value_arg);
  void set_model_name(std::string_view value_arg);

  const std::string* os_version() const;
  void set_os_version(const std::string_view* value_arg);
  void set_os_version(std::string_view value_arg);

  const std::string* mac_address() const;
  void set_mac_address(const std::string_view* value_arg);
  void set_mac_address(std::string_view value_arg);

  const std::string* lines_per_screen() const;
  void set_lines_per_screen(const std::string_view* value_arg);
  void set_lines_per_screen(std::string_view value_arg);

  const std::string* chars_per_line() const;
  void set_chars_per_line(const std::string_view* value_arg);
  void set_chars_per_line(std::string_view value_arg);

  const std::string* app_name() const;
  void set_app_name(const std::string_view* value_arg);
  void set_app_name(std::string_view value_arg);

  const std::string* app_version() const;
  void set_app_version(const std::string_view* value_arg);
  void set_app_version(std::string_view value_arg);

  const std::string* wifi_mac() const;
  void set_wifi_mac(const std::string_view* value_arg);
  void set_wifi_mac(std::string_view value_arg);

  const ManageTouchscreenStatus* touchscreen() const;
  void set_touchscreen(const ManageTouchscreenStatus* value_arg);
  void set_touchscreen(const ManageTouchscreenStatus& value_arg);

  const ManageHardwareConfigurationBitmap* hardware_configuration_bitmap() const;
  void set_hardware_configuration_bitmap(const ManageHardwareConfigurationBitmap* value_arg);
  void set_hardware_configuration_bitmap(const ManageHardwareConfigurationBitmap& value_arg);

  const ManageAppActivated* app_activated() const;
  void set_app_activated(const ManageAppActivated* value_arg);
  void set_app_activated(const ManageAppActivated& value_arg);

  const std::string* license_expiry() const;
  void set_license_expiry(const std::string_view* value_arg);
  void set_license_expiry(std::string_view value_arg);

  const ManageProtocolFlag* protocol_flag() const;
  void set_protocol_flag(const ManageProtocolFlag* value_arg);
  void set_protocol_flag(const ManageProtocolFlag& value_arg);


 private:
  static ManageInitResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;
  std::optional<std::string> sn_;
  std::optional<std::string> model_name_;
  std::optional<std::string> os_version_;
  std::optional<std::string> mac_address_;
  std::optional<std::string> lines_per_screen_;
  std::optional<std::string> chars_per_line_;
  std::optional<std::string> app_name_;
  std::optional<std::string> app_version_;
  std::optional<std::string> wifi_mac_;
  std::optional<ManageTouchscreenStatus> touchscreen_;
  std::optional<ManageHardwareConfigurationBitmap> hardware_configuration_bitmap_;
  std::optional<ManageAppActivated> app_activated_;
  std::optional<std::string> license_expiry_;
  std::optional<ManageProtocolFlag> protocol_flag_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageGetSignatureResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageGetSignatureResponse();

  // Constructs an object setting all fields.
  explicit ManageGetSignatureResponse(
    const std::string* response_code,
    const std::string* response_message,
    const std::string* signature_data);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);

  const std::string* signature_data() const;
  void set_signature_data(const std::string_view* value_arg);
  void set_signature_data(std::string_view value_arg);


 private:
  static ManageGetSignatureResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;
  std::optional<std::string> signature_data_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageUpdateResourceFileResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageUpdateResourceFileResponse();

  // Constructs an object setting all fields.
  explicit ManageUpdateResourceFileResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageUpdateResourceFileResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageSetApplePayVasParametersResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageSetApplePayVasParametersResponse();

  // Constructs an object setting all fields.
  explicit ManageSetApplePayVasParametersResponse(
    const std::string* response_code,
    const std::string* response_message);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);


 private:
  static ManageSetApplePayVasParametersResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;

};


// Generated class from Pigeon that represents data sent in messages.
class ManageSetVariableResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  ManageSetVariableResponse();

  // Constructs an object setting all fields.
  explicit ManageSetVariableResponse(
    const std::string* response_code,
    const std::string* response_message,
    const ManageMultiMerchant* multi_merchant);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);

  const ManageMultiMerchant* multi_merchant() const;
  void set_multi_merchant(const ManageMultiMerchant* value_arg);
  void set_multi_merchant(const ManageMultiMerchant& value_arg);


 private:
  static ManageSetVariableResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkManageApi;
  friend class POSLinkManageApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;
  std::optional<ManageMultiMerchant> multi_merchant_;

};

class POSLinkManageApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  POSLinkManageApiCodecSerializer();
  inline static POSLinkManageApiCodecSerializer& GetInstance() {
    static POSLinkManageApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class POSLinkManageApi {
 public:
  POSLinkManageApi(const POSLinkManageApi&) = delete;
  POSLinkManageApi& operator=(const POSLinkManageApi&) = delete;
  virtual ~POSLinkManageApi() {}
  virtual void DeleteImage(
    const ManageDeleteImageRequest& req,
    std::function<void(ErrorOr<ManageDeleteImageResponse> reply)> result) = 0;
  virtual void DoSignature(
    const ManageDoSignatureRequest& req,
    std::function<void(ErrorOr<ManageDoSignatureResponse> reply)> result) = 0;
  virtual void VasPushData(
    const ManageVasPushDataRequest& req,
    std::function<void(ErrorOr<ManageVasPushDataResponse> reply)> result) = 0;
  virtual void Init(
    const ManageInitRequest& req,
    std::function<void(ErrorOr<ManageInitResponse> reply)> result) = 0;
  virtual void SetGoogleSmartTapParameters(
    const ManageSetGoogleSmartTapParametersRequest& req,
    std::function<void(ErrorOr<ManageSetGoogleSmartTapParametersResponse> reply)> result) = 0;
  virtual void CheckFile(
    const ManageCheckFileRequest& req,
    std::function<void(ErrorOr<ManageCheckFileResponse> reply)> result) = 0;
  virtual void ClearCardBuffer(
    const ManageClearCardBufferRequest& req,
    std::function<void(ErrorOr<ManageClearCardBufferResponse> reply)> result) = 0;
  virtual void SetApplePayVasParameters(
    const ManageSetApplePayVasParametersRequest& req,
    std::function<void(ErrorOr<ManageSetApplePayVasParametersResponse> reply)> result) = 0;
  virtual void GetSignature(
    const ManageGetSignatureRequest& req,
    std::function<void(ErrorOr<ManageGetSignatureResponse> reply)> result) = 0;
  virtual void ResetScreen(
    const ManageResetScreenRequest& req,
    std::function<void(ErrorOr<ManageResetScreenResponse> reply)> result) = 0;
  virtual void GetVariable(
    const ManageGetVariableRequest& req,
    std::function<void(ErrorOr<ManageGetVariableResponse> reply)> result) = 0;
  virtual void UpdateResourceFile(
    const ManageUpdateResourceFileRequest& req,
    std::function<void(ErrorOr<ManageUpdateResourceFileResponse> reply)> result) = 0;
  virtual void Reboot(
    const ManageRebootRequest& req,
    std::function<void(ErrorOr<ManageRebootResponse> reply)> result) = 0;
  virtual void SetVariable(
    const ManageSetVariableRequest& req,
    std::function<void(ErrorOr<ManageSetVariableResponse> reply)> result) = 0;

  // The codec used by POSLinkManageApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `POSLinkManageApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    POSLinkManageApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  POSLinkManageApi() = default;

};
}  // namespace POSLinkManage
#endif  // PIGEON_POSLINKMANAGE_H_
