// Autogenerated from Pigeon (v10.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_POSLINKPAYLOAD_H_
#define PIGEON_POSLINKPAYLOAD_H_
#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <map>
#include <optional>
#include <string>

namespace POSLinkPayload {


// Generated class from Pigeon.

class FlutterError {
 public:
  explicit FlutterError(const std::string& code)
    : code_(code) {}
  explicit FlutterError(const std::string& code, const std::string& message)
    : code_(code), message_(message) {}
  explicit FlutterError(const std::string& code, const std::string& message, const flutter::EncodableValue& details)
    : code_(code), message_(message), details_(details) {}

  const std::string& code() const { return code_; }
  const std::string& message() const { return message_; }
  const flutter::EncodableValue& details() const { return details_; }

 private:
  std::string code_;
  std::string message_;
  flutter::EncodableValue details_;
};

template<class T> class ErrorOr {
 public:
  ErrorOr(const T& rhs) : v_(rhs) {}
  ErrorOr(const T&& rhs) : v_(std::move(rhs)) {}
  ErrorOr(const FlutterError& rhs) : v_(rhs) {}
  ErrorOr(const FlutterError&& rhs) : v_(std::move(rhs)) {}

  bool has_error() const { return std::holds_alternative<FlutterError>(v_); }
  const T& value() const { return std::get<T>(v_); };
  const FlutterError& error() const { return std::get<FlutterError>(v_); };

 private:
  friend class POSLinkPayloadApi;
  ErrorOr() = default;
  T TakeValue() && { return std::get<T>(std::move(v_)); }

  std::variant<T, FlutterError> v_;
};


// Generated class from Pigeon that represents data sent in messages.
class PayloadPayloadRequest {
 public:
  // Constructs an object setting all non-nullable fields.
  PayloadPayloadRequest();

  // Constructs an object setting all fields.
  explicit PayloadPayloadRequest(const std::string* payload);

  const std::string* payload() const;
  void set_payload(const std::string_view* value_arg);
  void set_payload(std::string_view value_arg);


 private:
  static PayloadPayloadRequest FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkPayloadApi;
  friend class POSLinkPayloadApiCodecSerializer;
  std::optional<std::string> payload_;

};


// Generated class from Pigeon that represents data sent in messages.
class PayloadPayloadResponse {
 public:
  // Constructs an object setting all non-nullable fields.
  PayloadPayloadResponse();

  // Constructs an object setting all fields.
  explicit PayloadPayloadResponse(
    const std::string* response_code,
    const std::string* response_message,
    const std::string* payload);

  const std::string* response_code() const;
  void set_response_code(const std::string_view* value_arg);
  void set_response_code(std::string_view value_arg);

  const std::string* response_message() const;
  void set_response_message(const std::string_view* value_arg);
  void set_response_message(std::string_view value_arg);

  const std::string* payload() const;
  void set_payload(const std::string_view* value_arg);
  void set_payload(std::string_view value_arg);


 private:
  static PayloadPayloadResponse FromEncodableList(const flutter::EncodableList& list);
  flutter::EncodableList ToEncodableList() const;
  friend class POSLinkPayloadApi;
  friend class POSLinkPayloadApiCodecSerializer;
  std::optional<std::string> response_code_;
  std::optional<std::string> response_message_;
  std::optional<std::string> payload_;

};

class POSLinkPayloadApiCodecSerializer : public flutter::StandardCodecSerializer {
 public:
  POSLinkPayloadApiCodecSerializer();
  inline static POSLinkPayloadApiCodecSerializer& GetInstance() {
    static POSLinkPayloadApiCodecSerializer sInstance;
    return sInstance;
  }

  void WriteValue(
    const flutter::EncodableValue& value,
    flutter::ByteStreamWriter* stream) const override;

 protected:
  flutter::EncodableValue ReadValueOfType(
    uint8_t type,
    flutter::ByteStreamReader* stream) const override;

};

// Generated interface from Pigeon that represents a handler of messages from Flutter.
class POSLinkPayloadApi {
 public:
  POSLinkPayloadApi(const POSLinkPayloadApi&) = delete;
  POSLinkPayloadApi& operator=(const POSLinkPayloadApi&) = delete;
  virtual ~POSLinkPayloadApi() {}
  virtual void Payload(
    const PayloadPayloadRequest& req,
    std::function<void(ErrorOr<PayloadPayloadResponse> reply)> result) = 0;

  // The codec used by POSLinkPayloadApi.
  static const flutter::StandardMessageCodec& GetCodec();
  // Sets up an instance of `POSLinkPayloadApi` to handle messages through the `binary_messenger`.
  static void SetUp(
    flutter::BinaryMessenger* binary_messenger,
    POSLinkPayloadApi* api);
  static flutter::EncodableValue WrapError(std::string_view error_message);
  static flutter::EncodableValue WrapError(const FlutterError& error);

 protected:
  POSLinkPayloadApi() = default;

};
}  // namespace POSLinkPayload
#endif  // PIGEON_POSLINKPAYLOAD_H_
